# Generated by Django 5.2.13 on 2026-04-15 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AspirantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('target_exam', models.CharField(max_length=100)),
                ('is_refund_eligible', models.BooleanField(default=True)),
                ('refund_voided_reason', models.TextField(blank=True, null=True)),
                ('onboarding_completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sureshot_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LIVE_CLASS', 'Live Class Attendance'), ('MOCK_TEST', 'Mock Test Attempt'), ('ASSIGNMENT', 'Daily Target / Assignment'), ('EXAM_PROOF', 'Official Exam Admit Card/Scorecard')], max_length=20)),
                ('activity_name', models.CharField(max_length=255)),
                ('score_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_compliant', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='compliance_proofs/')),
                ('aspirant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_logs', to='tracker.aspirantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=40000.0, max_digits=8)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('aspirant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.aspirantprofile')),
            ],
        ),
    ]
