# Generated by Django 5.2.13 on 2026-05-12 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('is_mandatory', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='aspirantprofile',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aspirantprofile',
            name='target_level',
            field=models.IntegerField(default=4),
        ),
        migrations.CreateModel(
            name='MandatoryExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('exam_level', models.IntegerField(default=4)),
                ('application_form_submitted', models.BooleanField(default=False)),
                ('admit_card_submitted', models.BooleanField(default=False)),
                ('appeared_for_exam', models.BooleanField(default=False)),
                ('cleared_exam', models.BooleanField(default=False)),
                ('breached_exam_rules', models.BooleanField(default=False)),
                ('aspirant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatory_exams', to='tracker.aspirantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='task_submissions/')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('aspirant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.aspirantprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.task')),
            ],
        ),
    ]
