# Generated by Django 5.2.13 on 2026-05-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_task_aspirantprofile_is_selected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scheduled_time', models.DateTimeField()),
                ('meeting_link', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
